version: "3.9"
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env   # 👈 docker 里也会自动加载
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: erp
    ports:
      - "5432:5432"
